---
language: ruby
sudo: false
cache: bundler
before_install:
  - gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
gemfile:
  - gemfiles/6_0.gemfile
  - gemfiles/5_2.gemfile
notifications:
  email: false
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
    secure: ABKL9+QRkF2+B8kQicumx122YSivY0L4yIZnbr5PxoRkgWdUVqyDPmhkz6yL4vhu53dRciKRLel1r+6QZ7rGDxRA0sOOSVyOw3ciyGSgIUFPTe8hO/r4wVKjCqoqK35gzd96x8DUSXBNMoTxFbgAXr7EajMMX8FQY5KjIomVloA=
